### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Lokeinus** [Si-7/compcon_rus#1]
При попытке создать пилота выдает это
![Screenshot_2023-12-11-08-40-02-467_com android chrome](https://github.com/Si-7/compcon_rus/assets/153471988/9bc1bfac-bc23-42d9-a04f-5dd8a81cc8a8)

**Comment by Si-7** [comment]
Прости, что долго отвечал
Это проблема, которая возникает, когда Comp/Con находится в состоянии подключения к облачному аккаунту. Для решения нужно подождать, пока вход в аккаунт будет завершен.
